name = "community"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-09-15"
assets = { directory = "./.output/public/", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "community"
database_id = "53e4ab13-9df4-4745-9aa0-dd44188c9278"
migrations_dir = "server/db/migrations"

[[r2_buckets]]
binding = "BLOB"
bucket_name = "community"
