/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=backup/wrangler.toml --include-runtime=false --env-interface=BackupEnv backup/worker-configuration.d.ts` (hash: cd7e41fe0dbf37a5e48a175c0884f1d0)
interface __BaseEnv_BackupEnv {
	SOURCE_BUCKET: R2Bucket;
	BACKUP_BUCKET: R2Bucket;
	DATABASE_ID: "53e4ab13-9df4-4745-9aa0-dd44188c9278";
	BACKUP_WORKFLOW: Workflow<Parameters<import("./src/index").CommunityBackupWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_BackupEnv {}
}
interface BackupEnv extends __BaseEnv_BackupEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_ID">> {}
}
